name: healtcheck-loc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: LOC Analysis
      uses: softawaregmbh/healthcheck-loc-action@v1.0.0

    - name: Save as artifact
      uses: actions/upload-artifact@v2
      with:
        name: healthcheck-loc
        path: ./healthcheck-loc.json
